### ISSUE TITLE
How to Refactor BadExample.java

### ISSUE THREAD

**Issue by mesut** [philsttr/avoiding-reactor-meltdown#1]
Hi Philsttr,

I watched your presentation about avoiding meltdown reactor and I did not see any solution about to refactor [BadExample.java](https://github.com/philsttr/avoiding-reactor-meltdown/blob/master/src/main/java/meltdown/demo/BadExamples.java)
Could you add refactored solution for BadExample.java ? How we can refactor this problem?

Thank you

**Comment by philsttr** [comment]
I updated BadExamples.java with the corresponding good version

**Comment by mesut** [comment]
Thank you very much 🥇
